### ISSUE TITLE
Running errors

### ISSUE THREAD

**Issue by bkong1990** [tpfister/caffe-heatmap#4]
Hi, I tried your demo and I followed your code, It crushed every time when it entered the forwardprefilled() function. Do I need to install OpenCV before I install caffe? Thanks so much.

**Comment by tracer9** [comment]
Hi bkong1990, I am also tried to run the code. In my opinion, OpenCV is a must for installing caffe. Otherwise, the crush problem may not resulted from this, try the caffe's own example. I'm afraid you may not install it in a correct way.

**Comment by kshalini** [comment]
@tracer9  @tpfister 

i tried running the demo by modifying the code to Python. but in the final stage where I try to extract the labels of the conv5_fusion, am not able to get the 256x256x7 which lets us extract the joints. 

do you have any ideas / suggestions? is there any Python code for this prediction part that you can share? thanks in advance

**Comment by murthypramod** [comment]
@kshalini  Not sure,  if you got it working. I got the heatmap blob which are of  29x7x64x64.

**Comment by samouha** [comment]
I met the same error when compiling the demo of CaffeHeatmap; and I resolved it by changing "gpu_id" in the file "initCaffe.m" (/caffeheatmap_root/matlab/pose) to 0. Because my gpu_id device is set to 0 and in such file it is set to 3. So you have to change it in order to be convenient with you own GPU device. 
You can run the command in a terminal to know what is your gpu_id: $ nvidia-smi -q 
Hope this can help you :)

**Comment by bkong1990** [comment]
Thank you so much @samouha . You solved my problem.

**Comment by samouha** [comment]
you're welcome @bkong1990 :) 
Best regards.

**Comment by samouha** [comment]
you're welcome @bkong1990 <https://github.com/bkong1990> :)
Best regards.

2016-02-19 15:28 GMT+01:00 bkong1990 <notifications@github.com>:
